config/routes.rb
Rails.application.routes.draw do
  resources :students, except: [:destroy]
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
  post 'course_enroll', to: 'students_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  # Validations
  validates :course_code, presence: true, uniqueness: { ignore_case: false },
    length: { minimum: 3, maximum: 10 }
  validates :name, presence: true, length: { minimum: 10, maximum: 200 }
  validates :description, presence: true, length: { minimum: 25 }

  # Associations
  has_many :students_courses
  has_many :students, through: :students_courses
end

app/models/student.rb
class Student < ApplicationRecord
  before_save { self.email = email.downcase }

  # Validations
  validates :name, presence: true, length: { minimum: 5, maximum: 30 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false },
    length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }

  # Associations
  has_secure_password
  has_many :students_courses
  has_many :courses, through: :students_courses
end

app/models/students_course.rb
class StudentsCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user
  helper_method :current_user, :user_signed_in?

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def require_user
    if !user_signed_in?
      flash[:notice] = "You gats to be logged in"
      redirect_to login_path
    end
  end

  def user_signed_in?
    !!current_user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index
    @courses = Course.all
  end

  def new

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:create, :new]

  def create
    student = Student.find_by(email: params[:sessions][:email].downcase)
    if student && student.authenticate(params[:sessions][:password])
      session[:student_id] = student.id
      flash[:notice] = "Successfully logged in"
      redirect_to student
    else
      flash.now[:notice] = "Invalid credentials"
      render 'new'
    end
  end

  def delete
    session[:student_id] = nil
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end

  def new

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :get_student, only: [:edit, :update, :show]
  before_action :self_identify, only: [:edit, :update]

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(white_list_params)
    if @student.save
      flash[:notice] = 'Successfully signed up'
      redirect_to @student
    else
      flash[:alert] = 'Whoops! Something went wrong. Please try again'
      render 'new'
    end
  end

  def edit

  end

  def show

  end

  def update
    if @student.update(white_list_params)
      flash[:notice] = 'Successfully updated profile'
      redirect_to student_path(@student)
    else
      flash[:alert] = 'Whoops! Something went wrong. Please try again'
      render 'edit'
    end
  end

  private

  def get_student
    @student = Student.find(params[:id])
  end

  def self_identify
    if current_user != @student
      redirect_to student_path(current_user)
      flash[:notice] = 'Stop trying to reap where you did not sow'
    end
  end

  def white_list_params
    params.require(:student).permit(:name, :email, :password, :password_confrimation)
  end
end

app/controllers/students_courses_controller.rb
class StudentsCoursesController < ApplicationController
  def create
    course_to_enroll = Course.find(params[:course_id])
    unless current_user.courses.include?(course_to_enroll)
      StudentsCourse.create(course: course_to_enroll, student: current_user)
      flash[:notice] = "Successfully enrolled in #{course_to_enroll.name}"
      redirect_to current_user
    else
      flash[:notice] = "Whoops! Something went wrong :shrug:"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_link
    if user_signed_in?
      link_to('Log Out', logout_path, method: :delete)
    else
      link_to('Log In', login_path)
    end
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h2 class="center-align">Course Listing</h2>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.course_code %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <% if user_signed_in? && !current_user.courses.include?(course) %>
            <%= link_to 'ENROLL', course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <%= link_to 'INFO', '#' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<h2>This is the new course page</h2>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Weaver College</h5>
        <p class="grey-text text-lighten-4">Redefining the way the next generation of technologists are trained.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2020 Weaver College
    <a class="grey-text text-lighten-4 right" href="#!">Learn more</a>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <% if user_signed_in? %>
      <li><%= link_to 'Profile', student_path(current_user) %></li>
    <% end %>
    <li><%= session_link %></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <% if user_signed_in? %>
      <li><%= link_to 'Profile', student_path(current_user) %></li>
    <% end %>
    <li><%= session_link %></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to 'Weaver Tech', root_path, class: 'brand-logo right' %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <% if !user_signed_in?  %>
            <li><%= link_to 'Sign Up', new_student_path %></li>
          <% end %>
          <li><%= link_to 'Courses', root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Students', students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav" id="mobile-demo">
          <% if !user_signed_in?  %>
            <li><%= link_to 'Sign Up', new_student_path %></li>
          <% end %>
          <li><%= link_to 'Courses', root_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to 'Students', students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <%= message %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weaver College Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'  %>
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>This is the about page</h2>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <%= pluralize(obj.errors.count, 'error') %>
            occured while processing request:
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li> <%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? 'Sign Up' : 'Edit Profile' %></h3>
        <div class="row">
          <%= form_for (@student), html: { class: 'col s12 '} do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: 'Kerry Washington', autofocus: true %>
                <%= f.label :name, class: 'active' %> 
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, autocomplete: 'email', placeholder: 'email@example.com' %>
                <%= f.label :email, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: 'password' %>
                <%= f.label :password, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: 'confirm password' %>
                <%= f.label :confirm_password, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? 'Sign Up<i class="material-icons right">arrow_forward</i>'.html_safe : 'Update', class: 'btn orange waves-effect waves-light center') %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h2 class="center-align">Student Listing</h2>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><strong>Name: </strong><%= student.name %></span>
          <span class="card-title"><small><strong>Email: </strong><%= student.email %></span></small>
          <p><%= 'Registered ' + time_ago_in_words(student.created_at) %></p>
        </div>
        <div class="card-action">
          <%= link_to 'PROFILE', student_path(student) %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <div class="col s5 m5">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><strong>Name: </strong><%= @student.name %></span>
        <span class="card-title"><small><strong>Email: </strong><%= @student.email %></span></small>
        <p><%= 'Registered ' + time_ago_in_words(@student.created_at) %></p>
      </div>
    </div>
    <% if current_user == @student %>
      <%= link_to 'Edit Profile<i class="material-icons right">create</i>'.html_safe,
        edit_student_path(@student), class: 'waves-effect waves-light btn' %>
    <% end %>
  </div>

  <div class="col s7 m7">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><strong>Courses:</span>
        <% if @student.courses.empty? %>
          None
        <% else %>
          <ul>
            <% @student.courses.each do |course| %>
              <li><%= course.course_code %>: <%= course.name %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>